<?php

namespace Database\Seeders;

use App\Models\Medicine;
use Illuminate\Database\Seeder;

class PharmacySeeder extends Seeder
{
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Amoxicillin', 'generic_name' => 'Amoxicillin Trihydrate',
                'brand' => 'Amoxil', 'category' => 'Antibiotic', 'dosage_form' => 'Capsule',
                'dosage_strength' => 500, 'dosage_unit' => 'mg', 'weight_grams' => 0.6,
                'manufacturer' => 'GlaxoSmithKline', 'batch_number' => 'AMX-2024-001',
                'manufacture_date' => '2024-01-15', 'expiry_date' => '2026-01-15',
                'stock_quantity' => 200, 'reorder_level' => 30, 'unit_price' => 8.50,
                'selling_price' => 12.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => true,
                'description' => 'Broad-spectrum antibiotic used to treat bacterial infections.',
                'side_effects' => 'Nausea, diarrhea, skin rash, allergic reactions.',
                'contraindications' => 'Penicillin allergy, mononucleosis.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Paracetamol', 'generic_name' => 'Acetaminophen',
                'brand' => 'Biogesic', 'category' => 'Analgesic/Antipyretic', 'dosage_form' => 'Tablet',
                'dosage_strength' => 500, 'dosage_unit' => 'mg', 'weight_grams' => 0.55,
                'manufacturer' => 'Unilab', 'batch_number' => 'PCM-2024-002',
                'manufacture_date' => '2024-02-01', 'expiry_date' => '2027-02-01',
                'stock_quantity' => 500, 'reorder_level' => 50, 'unit_price' => 2.00,
                'selling_price' => 4.50, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Used for relief of mild to moderate pain and fever.',
                'side_effects' => 'Rare: liver damage with overdose.',
                'contraindications' => 'Severe liver disease.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Metformin', 'generic_name' => 'Metformin Hydrochloride',
                'brand' => 'Glucophage', 'category' => 'Antidiabetic', 'dosage_form' => 'Tablet',
                'dosage_strength' => 500, 'dosage_unit' => 'mg', 'weight_grams' => 0.65,
                'manufacturer' => 'Merck', 'batch_number' => 'MET-2024-003',
                'manufacture_date' => '2024-03-01', 'expiry_date' => '2026-03-01',
                'stock_quantity' => 8, 'reorder_level' => 20, 'unit_price' => 5.00,
                'selling_price' => 9.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => true,
                'description' => 'First-line medication for type 2 diabetes.',
                'side_effects' => 'Nausea, vomiting, diarrhea, lactic acidosis (rare).',
                'contraindications' => 'Renal impairment, liver disease.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Vitamin C', 'generic_name' => 'Ascorbic Acid',
                'brand' => 'Ceelin', 'category' => 'Vitamin/Supplement', 'dosage_form' => 'Tablet',
                'dosage_strength' => 500, 'dosage_unit' => 'mg', 'weight_grams' => 0.5,
                'manufacturer' => 'Unilab', 'batch_number' => 'VTC-2024-004',
                'manufacture_date' => '2024-01-01', 'expiry_date' => '2026-12-31',
                'stock_quantity' => 300, 'reorder_level' => 40, 'unit_price' => 3.00,
                'selling_price' => 6.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Essential vitamin for immune support and antioxidant protection.',
                'side_effects' => 'Stomach upset at high doses.',
                'contraindications' => 'Kidney stones history.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Losartan', 'generic_name' => 'Losartan Potassium',
                'brand' => 'Cozaar', 'category' => 'Antihypertensive', 'dosage_form' => 'Tablet',
                'dosage_strength' => 50, 'dosage_unit' => 'mg', 'weight_grams' => 0.45,
                'manufacturer' => 'Merck', 'batch_number' => 'LOS-2024-005',
                'manufacture_date' => '2024-04-01', 'expiry_date' => '2026-04-01',
                'stock_quantity' => 5, 'reorder_level' => 15, 'unit_price' => 12.00,
                'selling_price' => 18.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => true,
                'description' => 'Used to treat high blood pressure and protect kidneys in diabetics.',
                'side_effects' => 'Dizziness, hyperkalemia, renal impairment.',
                'contraindications' => 'Pregnancy, bilateral renal artery stenosis.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Salbutamol', 'generic_name' => 'Albuterol',
                'brand' => 'Ventolin', 'category' => 'Bronchodilator', 'dosage_form' => 'Inhaler',
                'dosage_strength' => 100, 'dosage_unit' => 'mcg', 'weight_grams' => 18.0,
                'manufacturer' => 'GSK', 'batch_number' => 'SAL-2024-006',
                'manufacture_date' => '2024-05-01', 'expiry_date' => '2026-05-01',
                'stock_quantity' => 45, 'reorder_level' => 10, 'unit_price' => 150.00,
                'selling_price' => 220.00, 'storage_condition' => 'Room Temperature, away from heat',
                'requires_prescription' => true,
                'description' => 'Relieves bronchospasm in asthma and COPD.',
                'side_effects' => 'Tremor, palpitations, headache.',
                'contraindications' => 'Hypersensitivity to salbutamol.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Cetirizine', 'generic_name' => 'Cetirizine Hydrochloride',
                'brand' => 'Zyrtec', 'category' => 'Antihistamine', 'dosage_form' => 'Tablet',
                'dosage_strength' => 10, 'dosage_unit' => 'mg', 'weight_grams' => 0.4,
                'manufacturer' => 'UCB Pharma', 'batch_number' => 'CTZ-2024-007',
                'manufacture_date' => '2024-03-10', 'expiry_date' => '2027-03-10',
                'stock_quantity' => 150, 'reorder_level' => 25, 'unit_price' => 5.00,
                'selling_price' => 9.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Used to relieve allergy symptoms such as runny nose, sneezing, and itchy eyes.',
                'side_effects' => 'Drowsiness, dry mouth, headache.',
                'contraindications' => 'Severe renal impairment.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Omeprazole', 'generic_name' => 'Omeprazole',
                'brand' => 'Losec', 'category' => 'Antacid/PPI', 'dosage_form' => 'Capsule',
                'dosage_strength' => 20, 'dosage_unit' => 'mg', 'weight_grams' => 0.5,
                'manufacturer' => 'AstraZeneca', 'batch_number' => 'OMP-2024-008',
                'manufacture_date' => '2024-02-15', 'expiry_date' => '2026-08-15',
                'stock_quantity' => 120, 'reorder_level' => 20, 'unit_price' => 10.00,
                'selling_price' => 16.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Reduces stomach acid. Used for GERD, ulcers, and acid reflux.',
                'side_effects' => 'Headache, nausea, diarrhea, abdominal pain.',
                'contraindications' => 'Hypersensitivity to proton pump inhibitors.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Ibuprofen', 'generic_name' => 'Ibuprofen',
                'brand' => 'Advil', 'category' => 'NSAID/Analgesic', 'dosage_form' => 'Tablet',
                'dosage_strength' => 400, 'dosage_unit' => 'mg', 'weight_grams' => 0.55,
                'manufacturer' => 'Pfizer', 'batch_number' => 'IBU-2024-009',
                'manufacture_date' => '2024-04-20', 'expiry_date' => '2027-04-20',
                'stock_quantity' => 250, 'reorder_level' => 30, 'unit_price' => 4.00,
                'selling_price' => 7.50, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Used for pain relief, fever reduction, and anti-inflammation.',
                'side_effects' => 'Stomach upset, nausea, GI bleeding with prolonged use.',
                'contraindications' => 'Peptic ulcer, renal impairment, aspirin allergy.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Amlodipine', 'generic_name' => 'Amlodipine Besylate',
                'brand' => 'Norvasc', 'category' => 'Antihypertensive', 'dosage_form' => 'Tablet',
                'dosage_strength' => 5, 'dosage_unit' => 'mg', 'weight_grams' => 0.4,
                'manufacturer' => 'Pfizer', 'batch_number' => 'AML-2024-010',
                'manufacture_date' => '2024-01-20', 'expiry_date' => '2026-07-20',
                'stock_quantity' => 180, 'reorder_level' => 25, 'unit_price' => 8.00,
                'selling_price' => 14.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => true,
                'description' => 'Calcium channel blocker used to treat high blood pressure and chest pain.',
                'side_effects' => 'Swelling of ankles, flushing, dizziness, palpitations.',
                'contraindications' => 'Severe hypotension, aortic stenosis.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Diatabs', 'generic_name' => 'Attapulgite',
                'brand' => 'Diatabs', 'category' => 'Antidiarrheal', 'dosage_form' => 'Tablet',
                'dosage_strength' => 750, 'dosage_unit' => 'mg', 'weight_grams' => 0.85,
                'manufacturer' => 'Unilab', 'batch_number' => 'DIA-2024-011',
                'manufacture_date' => '2024-03-01', 'expiry_date' => '2027-03-01',
                'stock_quantity' => 200, 'reorder_level' => 30, 'unit_price' => 3.50,
                'selling_price' => 6.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Used to treat diarrhea by absorbing excess fluid in the intestines.',
                'side_effects' => 'Constipation with prolonged use.',
                'contraindications' => 'Bowel obstruction.',
                'status' => 'active', 'supplied_by' => null,
            ],
            [
                'name' => 'Mefenamic Acid', 'generic_name' => 'Mefenamic Acid',
                'brand' => 'Ponstan', 'category' => 'NSAID/Analgesic', 'dosage_form' => 'Capsule',
                'dosage_strength' => 500, 'dosage_unit' => 'mg', 'weight_grams' => 0.6,
                'manufacturer' => 'Pfizer', 'batch_number' => 'MEF-2024-012',
                'manufacture_date' => '2024-04-01', 'expiry_date' => '2027-04-01',
                'stock_quantity' => 160, 'reorder_level' => 25, 'unit_price' => 5.50,
                'selling_price' => 10.00, 'storage_condition' => 'Room Temperature',
                'requires_prescription' => false,
                'description' => 'Used for mild to moderate pain relief including menstrual pain and headache.',
                'side_effects' => 'Stomach upset, nausea, diarrhea, GI bleeding.',
                'contraindications' => 'Peptic ulcer, renal impairment, inflammatory bowel disease.',
                'status' => 'active', 'supplied_by' => null,
            ],
        ];

        foreach ($medicines as $med) {
            Medicine::create($med);
        }
    }
}
